---
title: "Isopod"
output: html_document
---

```{r library, include=FALSE}
library(tidyverse)
library(knitr) #making tables
library(leaflet)
library(tinytex) #may need for knitting pdf versions of .rmd file
library(ggplot2)
library(data.table)
library(lme4)
library(emmeans)
library(performance)
library(ggplot2)
library(see)
library(patchwork)
library(pbkrtest)
library(ggtext)
library(asbio)
library(ggfortify)
library(bootstrap)
library(GGally)
library(MuMIn)
library(readr)
library(data.table)
library(tidyverse)
library(lmerTest)
library(emmeans)
library(ggsn)
library(mapdata)
library(maptools)
library(rgdal)
```


```{r read in data, include=FALSE}
Isopod_data <- read.csv("./isopod.csv")
```


```{r view data}
View(Isopod_data)
```








```{r plot data}
as.factor(Moisture_Content)
plot(Time_Spent_Sec ~ Moisture_Content, data=Isopod_data)
```

```{r anova}
isopod.aov <- aov(Time_Spent_Sec ~ Moisture_Content, data = Isopod_data)
```

```{r summary}
summary(isopod.aov)
```
```{r read in data2, include=FALSE}
Isopod_data2 <- read.csv("./isopod_low_med.csv")
```

```{r anova2}
isopod_low_med.aov <- aov(Time_Spent_Sec_new ~ Moisture_Content_new, data = Isopod_data2)
```

```{r summary2}
summary(isopod_low_med.aov)
```